# Feature scaling Techniques for Machine learning 

In [19]:
# Importing libraries
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [2]:
# Loading dataset
Data=pd.read_csv("C:\\Users\\Shabu\\Desktop\\Height.Weight,Age.csv")
Data.head()

index   Height  Weight  Age
0       1     159      65   45
1       2     156      64   89
2       3     151      60   20
3       4     165      75   55
4       5     139      50   61

In [4]:
# Shape of the dataset
Data.shape

(20, 4)

In [5]:
# Splitting dependent and independent variable
X= Data.drop('Age', axis=1)
y=Data['Age']

In [6]:
# Splitting test and train dataset
from sklearn.model_selection import train_test_split
X_train, X_test,y_train, y_test = train_test_split(X,y ,random_state=3,test_size=0.10)

In [7]:
# X_train before scaling
X_train.head()

index   Height  Weight
1        2     156      64
17      18     162      62
4        5     139      50
16      17     159      63
6        7     161      70

## 1) Standardization

In [8]:
# Fit and transform using StandardScaler from sklearn
from sklearn.preprocessing import StandardScaler
SC = StandardScaler()
X_train_Scaled=SC.fit_transform(X_train)
X_train_Scaled

array([[-1.51635079,  0.40141708,  0.52692446],
       [ 1.28306606,  1.18965426,  0.1998679 ],
       [-0.99146013, -1.83192159, -1.76247148],
       [ 1.1081025 ,  0.79553567,  0.36339618],
       [-0.64153303,  1.0582814 ,  1.50809415],
       [-0.46656947, -0.64956582, -1.10835835],
       [ 0.93313895, -0.51819296, -0.45424523],
       [ 0.40824829, -1.70054873, -1.5989432 ],
       [-0.11664237,  0.53278994,  0.36339618],
       [ 0.23328474, -1.04368441, -0.45424523],
       [ 1.63299316, -0.91231155, -0.61777351],
       [ 1.45802961,  0.66416281,  0.52692446],
       [ 0.58321184, -0.3868201 , -0.29071694],
       [-0.81649658, -1.04368441, -0.94483007],
       [-1.69131435,  0.79553567,  0.69045274],
       [-0.29160592,  0.79553567,  0.1998679 ],
       [-1.16642369,  1.58377285,  2.32573556],
       [ 0.05832118,  0.27004422,  0.52692446]])

In [9]:
# Scaled test data
X_test_Scaled=SC.fit_transform(X_test)
X_test_Scaled

array([[ 1.,  1.,  0.],
       [-1., -1.,  0.]])

In [10]:
# Building a Linear regression model after standardization
from sklearn.linear_model import LinearRegression
LR = LinearRegression()
LR.fit(X_train_Scaled,y_train)
predict = LR.predict(X_test_Scaled)

## 2) MinMax Scaler

In [24]:
# Fit and transform using MinMaxScaler from sklearn
from sklearn.preprocessing import MinMaxScaler
MMS = StandardScaler()
Scaled_X_train=MMS.fit_transform(X_train)
X_train_Scaled

array([[-1.51635079,  0.40141708,  0.52692446],
       [ 1.28306606,  1.18965426,  0.1998679 ],
       [-0.99146013, -1.83192159, -1.76247148],
       [ 1.1081025 ,  0.79553567,  0.36339618],
       [-0.64153303,  1.0582814 ,  1.50809415],
       [-0.46656947, -0.64956582, -1.10835835],
       [ 0.93313895, -0.51819296, -0.45424523],
       [ 0.40824829, -1.70054873, -1.5989432 ],
       [-0.11664237,  0.53278994,  0.36339618],
       [ 0.23328474, -1.04368441, -0.45424523],
       [ 1.63299316, -0.91231155, -0.61777351],
       [ 1.45802961,  0.66416281,  0.52692446],
       [ 0.58321184, -0.3868201 , -0.29071694],
       [-0.81649658, -1.04368441, -0.94483007],
       [-1.69131435,  0.79553567,  0.69045274],
       [-0.29160592,  0.79553567,  0.1998679 ],
       [-1.16642369,  1.58377285,  2.32573556],
       [ 0.05832118,  0.27004422,  0.52692446]])

In [25]:
# Scaled test data
X_test_Scaled=MMS.fit_transform(X_test)
X_test_Scaled

array([[ 1.,  1.,  0.],
       [-1., -1.,  0.]])

## 3) Absolute Maximum Scaling

In [16]:
# Fit and transform using MaxAbsScaler from sklearn
from sklearn.preprocessing import MaxAbsScaler
MAS = MaxAbsScaler()
NewData = MAS.fit_transform(Data)

In [18]:
print(NewData)

[[0.05       0.96363636 0.86666667 0.49450549]
 [0.1        0.94545455 0.85333333 0.97802198]
 [0.15       0.91515152 0.8        0.21978022]
 [0.2        1.         1.         0.6043956 ]
 [0.25       0.84242424 0.66666667 0.67032967]
 [0.3        0.87878788 0.73333333 0.58241758]
 [0.35       0.97575758 0.93333333 1.        ]
 [0.4        0.8969697  0.72       0.52747253]
 [0.45       0.96363636 0.82666667 0.50549451]
 [0.5        0.95151515 0.84       0.98901099]
 [0.55       0.93939394 0.85333333 0.93406593]
 [0.6        0.87878788 0.77333333 0.61538462]
 [0.65       0.84848485 0.68       0.68131868]
 [0.7        0.90909091 0.78666667 0.63736264]
 [0.75       0.96969697 0.8        0.53846154]
 [0.8        0.9030303  0.77333333 0.56043956]
 [0.85       0.96363636 0.84       0.62637363]
 [0.9        0.98181818 0.82666667 0.58241758]
 [0.95       0.95757576 0.85333333 0.86813187]
 [1.         0.88484848 0.76       0.53846154]]


## 4) Robust Scaling

In [22]:
# Fit and transform using RobustScaler from sklearn
RS = preprocessing.RobustScaler()
RobustData = RS.fit_transform(Data)
print(RobustData)

[[-1.          0.30434783  0.64       -0.60869565]
 [-0.89473684  0.04347826  0.48        1.94202899]
 [-0.78947368 -0.39130435 -0.16       -2.05797101]
 [-0.68421053  0.82608696  2.24       -0.02898551]
 [-0.57894737 -1.43478261 -1.76        0.31884058]
 [-0.47368421 -0.91304348 -0.96       -0.14492754]
 [-0.36842105  0.47826087  1.44        2.05797101]
 [-0.26315789 -0.65217391 -1.12       -0.43478261]
 [-0.15789474  0.30434783  0.16       -0.55072464]
 [-0.05263158  0.13043478  0.32        2.        ]
 [ 0.05263158 -0.04347826  0.48        1.71014493]
 [ 0.15789474 -0.91304348 -0.48        0.02898551]
 [ 0.26315789 -1.34782609 -1.6         0.37681159]
 [ 0.36842105 -0.47826087 -0.32        0.14492754]
 [ 0.47368421  0.39130435 -0.16       -0.37681159]
 [ 0.57894737 -0.56521739 -0.48       -0.26086957]
 [ 0.68421053  0.30434783  0.32        0.08695652]
 [ 0.78947368  0.56521739  0.16       -0.14492754]
 [ 0.89473684  0.2173913   0.48        1.36231884]
 [ 1.         -0.82608696 -0.64